---
title: "Income distribution by race"
author: "Matthew Pancia"
date: "9/28/2017"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(survey)
library(magrittr)
library(dplyr)
library(mitools)
main_data <- readRDS(here("data", "scf 2016.rds"))
replicate_data <- readRDS(here("data", "scf 2016 rw.rds"))
```

```{r}
main_design <- 
	svrepdesign( 
		weights = ~wgt , 
		repweights = replicate_data[ , -1 ] , 
		data = imputationList( main_data ) , 
		scale = 1 ,
		rscales = rep( 1 / 998 , 999 ) ,
		mse = TRUE ,
		type = "other" ,
		combined.weights = TRUE
	)
  
```

The Codebook from The Fed around this data codes reported primary/secondary race as two variables: `X6809`, `X6810`:

```
                     1.    *WHITE (INCLUDE MIDDLE EASTERN/ARAB WITH WHITE);
                            Caucasian
                     2.    *BLACK/AFRICAN-AMERICAN
                     3.    *HISPANIC/LATINO
                     4.    *ASIAN
                     5.    *AMERICAN INDIAN/ALASKA NATIVE
                     6.    *NATIVE HAWAIIAN/PACIFIC ISLANDER
                    -7.    *OTHER
                     0.     Inap. (/no further responses)
                *********************************************************
                    FOR THE PUBLIC DATA SET:
                    ONLY X6809 AND X6810 ARE INCLUDED.
                    FOR X6809, CODES 4, 5, AND 6 ARE
                    COMBINED WITH CODE -7.
                    IF AN ADDITIONAL RESPONSE WAS GIVEN IN X6810-X6814,
                    X6810 IS SET TO 1; OTHERWISE X6810 IS SET TO 5.
                *********************************************************
```



```{r message=FALSE, warning=FALSE}
filtered_design <- subset(main_design, race != 5)
quantile_vector <- seq(0, 1, .01)
total_income_pctiles <- quantile_vector %>% 
  lapply(function(x){lodown:::scf_MIcombine( 
  with( filtered_design , svyquantile( ~ income , x ) ) 
)}
) %>%
  lapply(function(x) x$coefficients) %>%
  unlist %>% 
  data.frame(total_ntile = quantile_vector, total_ntile_value = .)
```

```{r}
total_income_pctiles
```

```{r}
racial_income_pctiles <- lodown:::scf_MIcombine( 
  with( filtered_design ,
	svyby( 
		~ income , ~ as.factor(race)  , svyquantile , quantile_vector, se=FALSE
	) ) )
racial_income_pctiles %<>% 
  .$coefficients %>% 
  data.frame(variable = names(.), racial_ntile = .) %>% 
  tidyr::separate(variable, c("race", "race_ntile_value"), sep = ":V")
racial_income_pctiles$total_ntile <- findInterval(racial_income_pctiles$racial_ntile_value, total_income_pctiles$total_ntile_value)
```


# Plots

```{r}
  racial_income_pctiles %>% 
  mutate(race = forcats::fct_recode(race, 
                                    White = "1", 
                                    Black = "2", 
                                    Latino = "3")) %>%
  ggplot() + 
  geom_smooth(aes(x = as.numeric(race_ntile), y = total_ntile, color = race), 
              se=FALSE, 
              span = .1) + 
  geom_segment(data=data.frame(x=0, y=0, xend = 100, yend=100),
               aes(x = x, y = y, xend = xend, yend = yend, color="Equality"), 
               linetype = "dashed", show.legend = TRUE) + 
  scale_color_colorblind() + 
  xlab("Racial Wealth Percentile") + 
  ylab("Overall Wealth Percentile") + 
  ggtitle("Racial Wealth Percentile by Overall Wealth Percentile (2016)") + 
  labs(caption = "Source: Survey of Consumer Finances") + 
  theme_ipsum(grid = "Y") +
  theme(legend.title = element_blank()) 
```