---
title: "Income distribution by race"
author: "Matthew Pancia"
date: "9/28/2017"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(here)
library(ggplot2)
library(ggthemes) 
library(plotly)
library(hrbrthemes)
main_data <- readRDS(here("data", "main_data.rds"))
variable_labels <- readRDS(here("data", "variable_labels.rds"))
```

## 

Find racial codes.

```{r}
race_variables <- 
  variable_labels %>% 
  grep(pattern = "RACE", x = ., ignore.case = TRUE, value = TRUE) %>%
  names %>% 
  sapply(as.symbol)
race_variables
```

From the documentation: 

```
                     1.    *WHITE (INCLUDE MIDDLE EASTERN/ARAB WITH WHITE);
                            Caucasian
                     2.    *BLACK/AFRICAN-AMERICAN
                     3.    *HISPANIC/LATINO
                     4.    *ASIAN
                     5.    *AMERICAN INDIAN/ALASKA NATIVE
                     6.    *NATIVE HAWAIIAN/PACIFIC ISLANDER
                    -7.    *OTHER
                     0.     Inap. (/no further responses)
                *********************************************************
                    FOR THE PUBLIC DATA SET:
                    ONLY X6809 AND X6810 ARE INCLUDED.
                    FOR X6809, CODES 4, 5, AND 6 ARE
                    COMBINED WITH CODE -7.
                    IF AN ADDITIONAL RESPONSE WAS GIVEN IN X6810-X6814,
                    X6810 IS SET TO 1; OTHERWISE X6810 IS SET TO 5.
                *********************************************************

```

Create lookup:
```{r}
race_lookup <- tribble(
  ~X6809 , ~ X6810, ~race,
  1 , 1, "white",
  
  
)
```

Look at counts by race, basic summary stats:

```{r}
main_data %>% 
  group_by(!!!race_variables) %>% 
  summarize(total = n())
``` 

Get income variables 
```{r}
income_var <- 
  variable_labels %>% 
  grep(pattern = ".*TOTAL INCOME.*", x = ., ignore.case = TRUE, value = TRUE) %>%
  names %>% 
  sapply(as.symbol)
income_var
```

```{r}
positive_income <- main_data %>% 
  filter((!!!income_var) > 0)
nrow(positive_income)
```

```{r}
library(magrittr)
racial_summary <- positive_income %>% 
  filter((!!!race_variables[[1]]) > 0) %>%
  mutate(income_percentile = ntile(!!!income_var, 100)) %>%
  group_by(!!!race_variables[[1]]) %>% 
  mutate(racial_percentile = ntile(!!!income_var, 100)) %>%
  ungroup
racial_summary %<>% 
  select(race = !!!race_variables[[1]], racial_percentile, income_percentile) %>%
  mutate(race = as.factor(race)) %>%
  mutate(race = forcats::fct_recode(race, White = "1", Black = "2", Latino = "3")) %>%
  mutate(race = forcats::fct_relevel(race, "White", "Latino", "Black"))
```

```{r message=FALSE, warning=FALSE}
racial_plot <- racial_summary %>% 
  unique %>%
  ggplot(aes(x=racial_percentile, y=income_percentile)) +
  geom_smooth(aes(color =race), span = .05, se = FALSE) + 
  geom_segment(data=data.frame(x=0, y=0, xend = 100, yend=100),aes(x = x, y = y, xend = xend, yend = yend, color="Equality"), linetype = "dashed", show.legend = TRUE) + 
  scale_x_continuous(breaks = seq(0, 100, 20), limits = c(0,100), minor_breaks = NULL) + 
  scale_y_continuous(minor_breaks = NULL) + 
  xlab("Racial Wealth Percentile") + 
  ylab("Overall Wealth Percentile") + 
  ggtitle("Racial Wealth Percentile by Overall Wealth Percentile (2016)") + 
  labs(caption = "Source: Survey of Consumer Finances") + 
  theme_ipsum(grid = "Y") +
  theme(legend.title = element_blank()) + 
  scale_color_colorblind()
racial_plot
```

```{r}
library(plotly)
ggplotly(racial_plot)
```